# Minimal Kanagawa theme
format = """
îš­ $directory $git_branch$git_status
$character"""

# format = """
# $username@$hostname $directory $git_branch$git_status
# $character"""

[character]
success_symbol = "[â¯](fg:#957FB8)"
error_symbol = "[â¯](fg:#C34043)"

[username]
style_user = "fg:#7E9CD8"

[hostname]
style = "fg:#957FB8"

[directory]
style = "fg:#DCD7BA"
truncation_length = 2

[git_branch]
symbol = "ğŸŒ± "
style = "fg:#98BB6C"

[git_status]
style = "fg:#E6C384"
